# Generated by Django 5.2.5 on 2025-08-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('monthly_expenses', models.IntegerField(default=0)),
                ('goal', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
